version: '3.8'

services:
  db:
    image: postgres:14.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:  
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    