version: "3.7"

services:
  namenode:
    image: apache/hadoop:3.2.1
    hostname: namenode
    restart: always
    command: ["hdfs", "namenode"]
    ports:
      - "9870:9870"
      - "9000:9000"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop-cluster

  resourcemanager:
    image: apache/hadoop:3.2.1
    hostname: resourcemanager
    restart: always
    command: ["yarn", "resourcemanager"]
    ports:
      - "8088:8088"
    env_file:
      - ./hadoop.env
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop-cluster


